version: "3.2"

services:
  reverse-proxy:
    image: traefik:v2.0
    command: --api.insecure=true --providers.docker=true --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  catanie-test:
    image: "catanie-local"
    restart: always
    ports:
      - "3001:80"
  catamel-test:
    image: "catamel-local"
    volumes:
      - ./datasources.json:/usr/src/app/server/datasources.json
      - ./providers.json:/usr/src/app/server/providers.json
      - ./config.local.js:/usr/src/app/server/config.local.js
    ports:
      - "3000:3000"
